// this file was generated by serverless-auto-swagger
module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "Mimoo API - Service Tools",
    "version": "1"
  },
  "paths": {
    "/tools/{toolId}": {
      "delete": {
        "summary": "delete",
        "description": "Delete tools by toolId",
        "operationId": "delete.delete./tools/{toolId}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "toolId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      },
      "put": {
        "summary": "update",
        "description": "",
        "operationId": "update.put./tools/{toolId}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "toolId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      },
      "get": {
        "summary": "get",
        "description": "",
        "operationId": "get.get./tools/{toolId}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "toolId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/tools": {
      "post": {
        "summary": "create",
        "description": "",
        "operationId": "create.post./tools",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      },
      "get": {
        "summary": "list",
        "description": "",
        "operationId": "list.get./tools",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/register": {
      "post": {
        "summary": "register",
        "description": "",
        "operationId": "register.post./register",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/login": {
      "post": {
        "summary": "login",
        "description": "",
        "operationId": "login.post./login",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/getTag": {
      "get": {
        "summary": "getTag",
        "description": "",
        "operationId": "getTag.get./getTag",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    }
  },
  "definitions": {},
  "securityDefinitions": {}
};